import { PhotoboothItemProps } from '@/components/komukuna-event/BentoGridSpotlight';

// Photobooth Data
export const portfolioItems: PhotoboothItemProps[] = [
    {
        id: 1,
        badge: "Recommended",
        title: "Fitrah & Okta<br />Wedding",
        subtitle: "Live 360° Videobooth Experience",
        videoSrc: "/komukuna-event/process/video-bts1.mp4",
        templateImage: "/komukuna-event/process/hasil-template1.jpg",
        printImage: "/komukuna-event/process/hasil-cetak1.jpg",
        rawImage: "/komukuna-event/process/hasil-raw1.jpg",
        btsImage: "/komukuna-event/process/fotobts1.jpg",
    },
    {
        id: 2,
        badge: "New Release",
        title: "EX3 Basketball<br />Competition",
        subtitle: "Sport Event Photobooth & 360°",
        videoSrc: "/komukuna-event/process/video-bts2.mp4",
        templateImage: "/komukuna-event/process/hasil-template2.jpg",
        printImage: "/komukuna-event/process/hasil-cetak2.jpeg",
        rawImage: "/komukuna-event/process/hasil-raw2.jpg",
        btsImage: "/komukuna-event/process/fotobts2.JPG",
    },
    {
        id: 3,
        badge: "Special Event",
        title: "Event Stories<br />Highlight",
        subtitle: "Memorable Photobooth Moments",
        videoSrc: "/komukuna-event/process/video-bts3.mp4",
        templateImage: "/komukuna-event/process/hasil-template3.jpg",
        printImage: "/komukuna-event/process/hasil-cetak3.jpeg",
        rawImage: "/komukuna-event/process/hasil-raw3.jpg",
        btsImage: "/komukuna-event/process/fotobts3.jpg",
    }
];

// Real Data for Videobooth
export const videoItems = [
    { id: 1, title: 'Aksara 27 April 2025', src: '/portofolio/videobooth/Aksara 27 April 2025 @komukunastudio.mp4' },
    { id: 2, title: 'Aksara Janari Majapahit', src: '/portofolio/videobooth/Aksara Janari Majapahit 18 Januari 2025 @komukunastudio.mp4' },
    { id: 3, title: 'CAMPUSFAIR 2025 MAN 2 Mojokerto', src: '/portofolio/videobooth/CAMPUSFAIR2025 MAN 2 Mojokerto, 20 Januari 2025 @komukunastudio_2.mp4' },
    { id: 4, title: 'Carnaval Fun Kuripan', src: '/portofolio/videobooth/Carnaval Fun Kuripan Sumobito.mp4' },
    { id: 5, title: 'Dialog Cinta', src: '/portofolio/videobooth/Dialog Cinta 19-20 Juli 2025 @komukunastudio.mp4' },
    { id: 6, title: 'Forkopimda Cotton Run', src: '/portofolio/videobooth/Forkopimda Cotton Run 25-05-2025 @𝗸𝗼𝗺𝘂𝗸𝘂𝗻𝗮𝘀𝘁𝘂𝗱𝗶𝗼, 𝗢𝗥𝗗𝗘𝗥 𝗕𝗬 𝗪𝗔 𝟬𝟴𝟯𝟭-𝟮𝟮𝟴𝟲-𝟲𝟵𝟳𝟱_2.mp4' },
    { id: 7, title: 'Gemilang SMKN 1 Jombang', src: '/portofolio/videobooth/Gemilang SMKN 1 Jombang 24 Mei 2025 @komukunastudio.mp4' },
    { id: 8, title: 'Gesit Run Jombang', src: '/portofolio/videobooth/Gesit Run Jombang, 15 Juni 2025 @komukunastudio.mp4' },
    { id: 9, title: 'Halal bi Halal', src: '/portofolio/videobooth/Halal bi Halal 19 April 2025 @komukunastudio_2.mp4' },
    { id: 10, title: 'JOMBANG FEST 2025', src: '/portofolio/videobooth/JOMBANG FEST 2025 @komukunastudio Copy.mp4' },
    { id: 11, title: 'Jalan Ceria & Bazar Kapas Gading', src: '/portofolio/videobooth/Jalan Ceria & Bazar Kapas Gading SBY.mp4' },
    { id: 12, title: 'Jalan Santai Pondok Teratai', src: '/portofolio/videobooth/Jalan Santai Pondok Teratai.mp4' },
    { id: 13, title: 'Jalan Santai Warga Melati', src: '/portofolio/videobooth/Jalan Santai Warga Melati SBY.mp4' },
    { id: 14, title: 'Jombang Fun Run', src: '/portofolio/videobooth/Jombang Fun Run by @komukunastudio - SEWA WA 0895-3328-78425_2.mp4' },
    { id: 15, title: 'MAJAPAHIT RUN MJK', src: '/portofolio/videobooth/MAJAPAHIT RUN MJK - 22 JUNI 2025 - Videobooth by @komukunastudio.mp4' },
    { id: 16, title: 'PT Graha Mutu Persada', src: '/portofolio/videobooth/PT Graha Mutu Persada Mojokerto 28 Januari 2025 @komukunastudio_3.mp4' },
    { id: 17, title: 'Purnawiyata MI Khoiriyah', src: '/portofolio/videobooth/Purnawiyata MI Khoiriyah Sumobito 2024 Copy.mp4' },
    { id: 18, title: 'Purnawiyata MI Sabilul Huda', src: '/portofolio/videobooth/Purnawiyata MI Sabilul Huda Senden Jombang 19 Juni 2024.mp4' },
    { id: 19, title: 'Purnawiyata SMK Khoiriyah', src: '/portofolio/videobooth/Purnawiyata SMK Khoiriyah Sumobito 2024.mp4' },
    { id: 20, title: 'Reuni Descons 26 PPNS', src: '/portofolio/videobooth/Reuni Descons 26 PPNS 12 Januari 2025 @komukunastudio Copy.mp4' },
    { id: 21, title: 'SD Khatolik Wijana Jbg', src: '/portofolio/videobooth/SD Khatolik Wijana Jbg 2 Juni 2025 @komukunastudio.mp4' },
    { id: 22, title: 'SD MUHAMMADIYAH BRAWIJAYA', src: '/portofolio/videobooth/SD MUHAMMADIYAH BRAWIJAYA MJK 14 Juni 2025 @komukunastudio.mp4' },
    { id: 23, title: 'SD PLUS Muhammadiyah Brawijaya', src: '/portofolio/videobooth/SD PLUS Muhammadiyah Brawijaya Mojokerto.mp4' },
    { id: 24, title: 'SDN BALONGSARI 2 MJK', src: '/portofolio/videobooth/SDN BALONGSARI 2 MJK 11 Juni 2025 @komukunastudio.mp4' },
    { id: 25, title: 'SMABP 24 Mei 2025', src: '/portofolio/videobooth/SMABP 24 Mei 2025 @komukunastudio.mp4' },
    { id: 26, title: 'SMABP 25 Mei 2025', src: '/portofolio/videobooth/SMABP 25 Mei 2025 @komukunastudio Copy.mp4' },
    { id: 27, title: 'SMP Negeri 2 Sumobito', src: '/portofolio/videobooth/SMP Negeri 2 Sumobito, 16 Januari 2025 @komukunastudio.mp4' },
    { id: 28, title: 'Tasyakuran Khitan', src: '/portofolio/videobooth/Tasyakuran Khitan_2.mp4' },
    { id: 29, title: 'Wedding Lisa & Agus', src: '/portofolio/videobooth/Wedding Lisa & Agus 19 Juni 2025 by @komukunastudio.mp4' },
    { id: 30, title: 'Wedding Reza & Yola', src: '/portofolio/videobooth/Wedding Reza & Yola 07-07-2024.mp4' },
    { id: 31, title: 'Wisuda Tahfidz Akbar', src: "/portofolio/videobooth/Wisuda Tahfidz Akbar Raudhatul Qur'an Mojokerto 14 Desember 2024 @komukunastudio.mp4" },
];
